name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: python my_script.py
    steps:
      - uses: actions/checkout@v2
      - name: RobotFramework Test
        uses: roccoemanuelebonanno/robot-github-actions@main
        with:
          ref: refs/heads/release

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start robotframework test
        run: "robot --outputdir results --exclude Disabled ."
