name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: RobotFramework Test
        uses: roccoemanuelebonanno/robot-github-actions@main
        with:
          ref: refs/heads/release

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start robotframework test
        run: "robot --outputdir results --exclude Disabled ."

      - name: Upload test results
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: results
            path: ${{ github.workspace }}/results
